#!/usr/bin/env python3
"""Convert the skeleton enemy's frames into one 32x32 SNES sprite strip (single 16-colour palette),
feet-anchored so it doesn't slide as the rise/walk cycles play. Enemies are SMALL OBJs (32x32) so several
fit the 2KB enemy VRAM band (freed by the 64x64 moon). The source frames are 44x52, scaled down to fit.

Animations (in order; offsets emitted to src/skeleton_anim.h):
  rise  = skeleton-rise-clothed-1..6  (plays once, then -> walk)
  walk  = skeleton-clothed-1..8        (loops; the skeleton shuffles toward the player)

Output: res/skeleton.png (32 x 32*N strip). The Makefile runs gfx4snes -s 32 -R; enemy.c DMAs the current
32x32 frame (512 bytes) into a per-enemy slot of the enemy VRAM band.
"""
import os, sys
import numpy as np
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from adapt_assets import to_indexed

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EN   = os.path.join(ROOT, "assets", "gothicvania-cemetery-files", "Assets", "Characters", "Enemies")
BOX  = 32
SK   = os.path.join(EN, "skeleton")

ANIMS = [
    ("RISE", [os.path.join(SK, "skeleton-rise-clothed", f"skeleton-rise-clothed-{i}.png") for i in range(1, 7)]),
    ("WALK", [os.path.join(SK, "Sprites", "walk-clothed", f"skeleton-clothed-{i}.png") for i in range(1, 9)]),
]

# Uniform scale so the tallest frame fits BOX with a 1px margin (keeps every anim the same scale).
raws = [np.array(Image.open(p).convert("RGBA")) for _, ps in ANIMS for p in ps]
maxh = max(int(np.where(a[:, :, 3] > 0)[0].max() - np.where(a[:, :, 3] > 0)[0].min() + 1) for a in raws)
scale = (BOX - 1) / maxh

def conv(path):
    a = np.array(Image.open(path).convert("RGBA"))
    ys, xs = np.where(a[:, :, 3] > 0)
    # crop to content, scale uniformly, then place feet on the bottom row, centred horizontally
    crop = a[ys.min():ys.max() + 1, xs.min():xs.max() + 1]
    nw, nh = max(1, round(crop.shape[1] * scale)), max(1, round(crop.shape[0] * scale))
    s = np.array(Image.fromarray(crop).resize((nw, nh), Image.LANCZOS))
    s[s[:, :, 3] < 128] = 0
    out = np.zeros((BOX, BOX, 4), np.uint8)
    x0 = (BOX - nw) // 2
    y0 = BOX - nh                                    # feet on the bottom row
    xw = min(nw, BOX - x0); yh = min(nh, BOX - y0)
    out[y0:y0 + yh, x0:x0 + xw] = s[:yh, :xw]
    return out

frames, counts = [], {}
for name, paths in ANIMS:
    for p in paths:
        frames.append(conv(p))
    counts[name] = len(paths)

N = len(frames)
strip = np.zeros((BOX * N, BOX, 4), np.uint8)
for i, f in enumerate(frames):
    strip[i * BOX:i * BOX + BOX] = f
idx, nc = to_indexed(strip, transparent=True, budget=16, name="skeleton")
idx.save(os.path.join(ROOT, "res", "skeleton.png"))

with open(os.path.join(ROOT, "src", "skeleton_anim.h"), "w") as h:
    h.write("// generated by tools/adapt_enemy.py -- skeleton: 32x32 OBJ frames, feet-anchored\n")
    h.write(f"#define SK_FRAMES {N}\n")
    pos = 0
    for name, _ in ANIMS:
        h.write(f"#define SK_{name}_F {pos}\n#define SK_{name}_N {counts[name]}\n")
        pos += counts[name]
print(f"skeleton: {N} frames 32x32 (scale {scale:.2f}), palette {nc} colours")

# preview the strip on a dark sky, for eyeballing
prev = Image.new("RGB", (BOX, BOX * N), (24, 12, 40)); prev.paste(idx.convert("RGB"), (0, 0))
prev.resize((BOX * 4, BOX * N * 4 // 1, ), Image.NEAREST).save("/tmp/skeleton_strip.png")
