#!/usr/bin/env python3
"""Convert the hell-gato + ghost enemies into SNES sprite strips, mirroring adapt_enemy.py (skeleton).

Both emit a 128-wide strip (gfx4snes -s 64 -R packs each frame as a contiguous 16-wide 4 KB band -> two
64x64 halves, uploaded like the hero/skeleton). Native pixel size (no scaling) to match the hero.
  * gato  : 96x53 source, ~85px wide -> too wide for ONE 64x64 OBJ, so it spans the FULL 128-wide band
            (drawn as a 2-OBJ metasprite, left+right halves). Feet-anchored (it walks on the ground).
  * ghost : 37x65 source -> fits the LEFT 64x64 (right half blank, 1 OBJ). Centred -- it floats, and the
            AI bobs it vertically, so there's no ground contact to anchor on.

Output: res/{gato,ghost}.png (128 x 64*N) + src/{gato,ghost}_anim.h. /tmp/{name}_strip.png previews.
"""
import os, sys
import numpy as np
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from adapt_assets import to_indexed

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EN   = os.path.join(ROOT, "assets", "gothicvania-cemetery-files", "Assets", "Characters", "Enemies")
BOX, STRIP_W = 64, 128

def paste(path, x0, y0):
    """Paste a source frame into a 64x128 band at (x0,y0); hard alpha (OBJ index 0 = transparent)."""
    a = np.array(Image.open(path).convert("RGBA"))
    ch, cw = a.shape[0], a.shape[1]
    out = np.zeros((BOX, STRIP_W, 4), np.uint8)
    sx0, sy0 = max(0, -x0), max(0, -y0)
    dx0, dy0 = max(0, x0), max(0, y0)
    w = min(cw - sx0, STRIP_W - dx0); h = min(ch - sy0, BOX - dy0)
    seg = a[sy0:sy0 + h, sx0:sx0 + w].copy()
    seg[seg[:, :, 3] < 128] = 0
    out[dy0:dy0 + h, dx0:dx0 + w] = seg
    return out

def convert(name, paths, x0, y0, feet_by, anim):
    frames = [paste(p, x0, y0) for p in paths]
    N = len(frames)
    strip = np.zeros((BOX * N, STRIP_W, 4), np.uint8)
    for i, f in enumerate(frames):
        strip[i * BOX:i * BOX + BOX] = f
    idx, nc = to_indexed(strip, transparent=True, budget=16, name=name)
    idx.save(os.path.join(ROOT, "res", name + ".png"))
    up = name.upper()
    with open(os.path.join(ROOT, "src", name + "_anim.h"), "w") as h:
        h.write("// generated by tools/adapt_enemy2.py\n")
        h.write(f"#define {up}_FRAMES {N}\n#define {up}_FEET_BY {feet_by}\n")
        h.write(f"#define {up}_{anim}_F 0\n#define {up}_{anim}_N {N}\n")
    print(f"{name}: {N} frames 128-wide, feet@{feet_by}, palette {nc} colours")
    prev = Image.new("RGB", (STRIP_W, BOX * N), (24, 12, 40))
    prev.paste(idx.convert("RGB"), (0, 0))
    prev.resize((STRIP_W * 2, BOX * N * 2), Image.NEAREST).save(f"/tmp/{name}_strip.png")

# gato: 96-wide canvas centred in the 128 band (x0=16); feet (canvas row ~52) -> box row 60.
convert("gato", [os.path.join(EN, "hell-gato", "Sprites", f"hell-gato-{i}.png") for i in range(1, 5)],
        x0=16, y0=60 - 52, feet_by=60, anim="WALK")
# ghost: 37-wide canvas in the LEFT 64 (x0=13); 65 tall -> y0=0 clips the empty bottom row. Centred float.
convert("ghost", [os.path.join(EN, "ghost", "Sprites", f"ghost-{i}.png") for i in range(1, 5)],
        x0=13, y0=0, feet_by=60, anim="FLOAT")
