#ifndef GAME_H
#define GAME_H
/*---------------------------------------------------------------------------------
    game.h — shared declarations for the gothicvania TITLE -> PLAY -> END state machine.

    Each state (title.c / play.c / end.c) force-blanks, loads its OWN VRAM/palettes,
    runs its loop, and returns the next GameState; main.c (entry) dispatches them.
    Shared world/player state is defined in game.c. The level renderer's data + the
    reusable night-sky scene (moon + sky gradient) live in level.c; the hero in
    player.c. Per-tile collision data is generated into level_collision.c.
---------------------------------------------------------------------------------*/
#include <snes.h>
#include "hero_anim.h"                  // A_*/HERO_FEET_Y (generated by tools/adapt_hero.py)
#include "sky_params.h"                 // SKY_BACKDROP   (generated by tools/gen_sky_gradient.py)

// ---- level / world dimensions ----
#define LVL_COLS   300
#define LVL_ROWS   14
#define LVL_PXW    4800
#define CAM_MAX    (LVL_PXW - 256)
#define N_PAGES    19
#define PAGE_SPLIT 15

// VRAM layout (word addresses), tightly packed so NOTHING overlaps. Char bases are 0x1000-aligned,
// map bases 0x400-aligned. Each tile region is immediately followed by its OWN map inside the slack
// of its char-block, so BG2's tiles can never land under BG0's streamed map. Budget: parallax must
// stay <=768 tiles (it's 710) so BG2 tiles+map fit one 2-block pair. Total ends exactly at 0x8000.
//  0x0000 hero | 0x0800 moon | 0x1000 BG0 tiles | 0x1800 BG0 map | 0x2000 BG2 tiles(710)
//  | 0x3800 BG2 map | 0x4000 BG1 tiles(deco 880) | 0x7800 BG1 map.
#define HERO_VRAM  0x0000
#define MOON_VRAM  0x0800                  // moon OBJ band (tiles 128+)
#define BG0_TILES  0x1000                  // ground tiles (112)  -> 0x1000..0x1700
#define BG0_MAP    0x1800                  // ground (Main) tilemap, streamed
#define BG2_TILES  0x2000                  // parallax tiles (2bpp, 710) -> 0x2000..0x3630
#define BG2_MAP    0x3800                  // parallax tilemap
#define BG1_TILES  0x4000                  // deco tiles (880)  -> 0x4000..0x7700
#define BG1_MAP    0x7800                  // deco (Back) tilemap, streamed

// Title/end VRAM: no level is shown, so BG0/BG1 hold the overlays (logo / PRESS START / THANKS);
// the moon (OBJ) and mountains (BG2) reuse their play-scene addresses (force-blank reload between).
#define TITLE_PRESS_TILES 0x1000
#define TITLE_PRESS_MAP   0x1800
#define TITLE_LOGO_TILES  0x4000
#define TITLE_LOGO_MAP    0x7800

// player hitbox / sprite mapping. feetX/feetY = bottom-centre of the hitbox; the sprite's
// feet sit at frame-local (26,58) (set by tools/adapt_hero.py), 37 after an hflip.
#define HALF_W       6
#define BODY_HI      24
#define BODY_LO      4
#define SPR_OY       HERO_FEET_Y          // feet position inside the 64-tall sprite
#define HERO_LEFT_DX 64                   // the LEFT 64x64 sprite sits 64px left of the head
// 2-sprite hero: the strip is 128px wide (L|R), so gfx4snes packs each frame's two 64x64
// halves into one 4KB band -- L at gfxoffset 0, R at gfxoffset 8. One DMA per frame.
#define HERO_BANDSZ 4096
#define HBANK       7                     // 7 frames/bank: a(0..6) b(7..13) c(14..19)

#define JUMP_KEYS   (KEY_B | KEY_A)
#define ATTACK_KEYS (KEY_Y | KEY_X)

#define PPU_CLEAN_INIT 1   // clear the PPU's power-on garbage (colour math / windows / CGRAM); see main()

// ---- game state machine ----
typedef enum { ST_TITLE, ST_PLAY, ST_END } GameState;
GameState titleState(void);
GameState playState(void);
GameState endState(void);

// ---- shared world/player state (defined in game.c) ----
extern u16 camX, curA, curB;
extern s32 feetX, feetY;                              // 8.8 fixed-point pixels
extern s16 vx, vy;
extern u8  onGround, facing;
extern u16 jumpDir;

// ---- ROM data symbols (data.asm incbins) ----
extern unsigned char groundtiles, groundtilesend, groundpal, groundpalend;
extern unsigned char groundpagesA, groundpagesB;
extern unsigned char decotiles, decotilesend, decopal, decopalend;
extern unsigned char decopagesA, decopagesB;
extern unsigned char parallaxtiles, parallaxtilesend, parallaxpal, parallaxpalend, parallaxmap;
extern unsigned char sky_coldata;        // per-scanline COLOR-MATH ($2132) gradient table (NOT CGRAM)
extern unsigned char moontiles, moontilesend, moonpal, moonpalend;
extern unsigned char title_logo_tiles,  title_logo_tilesend,  title_logo_pal,  title_logo_map;
extern unsigned char title_press_tiles, title_press_tilesend, title_press_pal, title_press_map;
extern unsigned char title_thanks_tiles, title_thanks_tilesend, title_thanks_pal, title_thanks_map;
extern unsigned char hero_a, hero_b, hero_c, hero_pal, hero_palend;
extern const unsigned char levelCollision[];

// ---- music (snesmod soundbank, built by smconv from the Makefile's AUDIOFILES) ----
// Module indices follow the AUDIOFILES order (title.it -> 0, baroque.it -> 1). smconv also writes these
// to res/soundbank.h, but declaring them here avoids a build-order dependency on that generated header.
#define MOD_TITLE   0                  // demo's Title.mid -> the title screen loop
#define MOD_BAROQUE 1                  // Baroque.mid -> the in-game loop
extern char SOUNDBANK__;               // the linked soundbank; spcSetBank(&SOUNDBANK__)

// ---- level.c : streaming page sources + collision + shared night-sky scene ----
u8 *groundPage(u16 p);
u8 *decoPage(u16 p);
u8  cellv(s16 col, s16 row);
void setupMoon(u8 prio);       // moon+glow OBJ (prio 0 = behind mountains for play; 1 = in front for title)
void armSkyGradient(void);     // COLOR-MATH sky gradient on HDMA ch6 (shared by play + title)

// ---- player.c : the hero sprite ----
u8 *heroFrameSrc(u8 f);
void setupHero(void);          // load hero palette + frame 0 into the OBJ slot (OBJ0/OBJ4)

#endif
