#ifndef GAME_H
#define GAME_H
/*---------------------------------------------------------------------------------
    game.h — shared declarations for the gothicvania TITLE -> PLAY -> END state machine.

    Each state (title.c / play.c / end.c) force-blanks, loads its OWN VRAM/palettes,
    runs its loop, and returns the next GameState; main.c (entry) dispatches them.
    Shared world/player state is defined in game.c. The level renderer's data + the
    reusable night-sky scene (moon + sky gradient) live in level.c; the hero in
    player.c. Per-tile collision data is generated into level_collision.c.
---------------------------------------------------------------------------------*/
#include <snes.h>
#include "hero_anim.h"                  // A_*/HERO_FEET_Y (generated by tools/adapt_hero.py)
#include "skeleton_anim.h"              // SK_*           (generated by tools/adapt_enemy.py)
#include "sky_params.h"                 // SKY_BACKDROP   (generated by tools/gen_sky_gradient.py)

// ---- level / world dimensions ----
#define LVL_COLS   300
#define LVL_ROWS   14
#define LVL_PXW    4800
#define CAM_MAX    (LVL_PXW - 256)
#define N_PAGES    19
#define PAGE_SPLIT 15

// VRAM layout (word addresses), tightly packed so NOTHING overlaps. Char bases are 0x1000-aligned,
// map bases 0x400-aligned. Each tile region is immediately followed by its OWN map inside the slack
// of its char-block, so BG2's tiles can never land under BG0's streamed map. Budget: parallax must
// stay <=768 tiles (it's 710) so BG2 tiles+map fit one 2-block pair. Total ends exactly at 0x8000.
//  0x0000 hero | 0x0800 moon | 0x1000 BG0 tiles | 0x1800 BG0 map | 0x2000 BG2 tiles(710)
//  | 0x3800 BG2 map | 0x4000 BG1 tiles(deco 880) | 0x7800 BG1 map.
// OBJ region = tiles 0..511 (0x0000..0x2000; OBSEL gap 0 makes 256..511 contiguous at 0x1000). The
// ground used to sit in 0x1000..0x2000 -- it MOVED to 0x6000 (into space freed by deco tile-streaming)
// so the enemies get tiles 256..511 (0x1000..0x2000 = 8KB = 4 demo-size 64x64 sprites).
// CRITICAL: a 64x64 OBJ spans 8 grid-rows = 0x800 words (stride-16 tile read), NOT 0x400. So the moon
// (name 128) READS 0x0800..0x0F80, occupying the whole 0x0800..0x1000 block -- the enemy band MUST start
// at 0x1000 (not 0x0C00) or it overlaps the moon's lower half (skeleton renders in moon colours).
#define HERO_VRAM  0x0000                  // hero OBJ band  (tiles 0..127,   0x0000..0x0800)
#define MOON_VRAM  0x0800                  // moon OBJ band  (tiles 128..255, ONE 64x64 -> spans 0x0800..0x1000)
#define ENEMY_VRAM 0x1000                  // enemy OBJ band (tiles 256..511, 0x1000..0x2000 = 4x 64x64 slots)
#define BG0_TILES  0x6000                  // ground tiles (112) -> 0x6000..0x66C0 (moved out of the OBJ region)
#define BG0_MAP    0x6800                  // ground (Main) tilemap, streamed
#define BG2_TILES  0x2000                  // parallax tiles (2bpp, 710) -> 0x2000..0x3630
#define BG2_MAP    0x3800                  // parallax tilemap
#define BG1_TILES  0x4000                  // deco tile WINDOW (streamed): even-page slot 0x4000, odd-page
#define DECO_SLOT1 0x1000                  // slot at 0x5000; window = 0x4000..0x6000 (was 0x4000..0x7700 resident)
#define BG1_MAP    0x7800                  // deco (Back) tilemap, streamed

// Title/end VRAM: no level is shown, so BG0/BG1 hold the overlays (logo / PRESS START / THANKS);
// the moon (OBJ) and mountains (BG2) reuse their play-scene addresses (force-blank reload between).
#define TITLE_PRESS_TILES 0x1000
#define TITLE_PRESS_MAP   0x1800
#define TITLE_LOGO_TILES  0x4000
#define TITLE_LOGO_MAP    0x7800

// player hitbox / sprite mapping. feetX/feetY = bottom-centre of the hitbox; the sprite's
// feet sit at frame-local (26,58) (set by tools/adapt_hero.py), 37 after an hflip.
#define HALF_W       6
#define BODY_HI      24
#define BODY_LO      4
#define SPR_OY       HERO_FEET_Y          // feet position inside the 64-tall sprite
#define HERO_LEFT_DX 64                   // the LEFT 64x64 sprite sits 64px left of the head
// 2-sprite hero: the strip is 128px wide (L|R), so gfx4snes packs each frame's two 64x64
// halves into one 4KB band -- L at gfxoffset 0, R at gfxoffset 8. One DMA per frame.
#define HERO_BANDSZ 4096
#define HBANK       7                     // 7 frames/bank: a(0..6) b(7..13) c(14..19)

#define JUMP_KEYS   (KEY_B | KEY_A)
#define ATTACK_KEYS (KEY_Y | KEY_X)

#define PLAYER_HP   3                     // contact hits the hero survives; the 3rd -> GAME OVER

#define PPU_CLEAN_INIT 1   // clear the PPU's power-on garbage (colour math / windows / CGRAM); see main()

// ---- game state machine ----
typedef enum { ST_TITLE, ST_PLAY, ST_END, ST_GAMEOVER } GameState;
GameState titleState(void);
GameState playState(void);
GameState endState(void);
GameState gameoverState(void);   // shown on death (HP -> 0); START returns to the title

// ---- shared world/player state (defined in game.c) ----
extern u16 camX, curA, curB;
extern u16 respawns;                                 // pit-fall respawn count (hero dropped off the level)
extern u8  respawn;                                  // 1 when PLAY is re-entered after a respawn (skip audio reload)
extern s32 feetX, feetY;                              // 8.8 fixed-point pixels
extern s16 vx, vy;
extern u8  onGround, facing;
extern u16 jumpDir;

// ---- ROM data symbols (data.asm incbins) ----
extern unsigned char groundtiles, groundtilesend, groundpal, groundpalend;
extern unsigned char groundpagesA, groundpagesB;
extern unsigned char decopal, decopalend;                  // deco palette (block 1)
extern unsigned char deco_pt0, deco_pt1, deco_pt2;         // bank-packed per-page deco tiles (streamed)
extern unsigned char deco_pageinfo;                        // per-page (u16 section, u16 byteOffset, u16 count)
extern unsigned char deco_smapsA, deco_smapsB;             // window-local deco tilemaps (pages 0..14 / 15..18)
extern unsigned char parallaxtiles, parallaxtilesend, parallaxpal, parallaxpalend, parallaxmap;
extern unsigned char sky_coldata;        // per-scanline COLOR-MATH ($2132) gradient table (NOT CGRAM)
extern unsigned char moontiles, moontilesend, moonpal, moonpalend;
extern unsigned char title_logo_tiles,  title_logo_tilesend,  title_logo_pal,  title_logo_map;
extern unsigned char title_press_tiles, title_press_tilesend, title_press_pal, title_press_map;
extern unsigned char title_thanks_tiles, title_thanks_tilesend, title_thanks_pal, title_thanks_map;
extern unsigned char title_gameover_tiles, title_gameover_tilesend, title_gameover_pal, title_gameover_map;
extern unsigned char hero_a, hero_b, hero_c, hero_pal, hero_palend;
extern unsigned char skel_a, skel_b, skel_c, skelpal, skelpalend;  // skeleton: 128-wide 4KB bands a(0-6)/b(7-13)/c(14-18 death) + pal
extern const unsigned char levelCollision[];

// ---- audio (snesmod soundbank, built by smconv from the Makefile's AUDIOFILES) ----
// Module indices follow the AUDIOFILES order (effectssfx -> 0, title -> 1, baroque -> 2). smconv also
// writes these to res/soundbank.h, but declaring them here avoids a build-order dep on that header.
#define MOD_EFFECTSSFX 0               // the SFX bank (spcLoad it, then spcLoadEffect each effect)
#define MOD_TITLE      1               // Title.mid -> the title screen loop
#define MOD_BAROQUE    2               // Baroque.mid -> the in-game loop
// Sound-effect indices = the sample order in tools/adapt_sfx.py. Load with spcLoadEffect(SFX_x), play
// with spcEffect(4, SFX_x, vol) (pitch 4 = 16 kHz = original speed).
#define SFX_JUMP   0
#define SFX_ATTACK 1
#define SFX_HURT   2
#define SFX_KILL   3                   // enemies (Phase 3)
#define SFX_RISE   4                   // enemies (Phase 3)
extern char SOUNDBANK__;               // the linked soundbank; spcSetBank(&SOUNDBANK__)

// ---- level.c : streaming page sources + collision + shared night-sky scene ----
u8 *groundPage(u16 p);
u8 *decoSmap(u16 p);           // window-local deco tilemap for page p (DMA to BG1_MAP + slot)
u8 *decoPageTiles(u16 p);      // ROM addr of page p's deco tiles (DMA to BG1_TILES + parity slot)
u16 decoPageTileBytes(u16 p);  // byte size of page p's deco tiles (count * 32)
u8  cellv(s16 col, s16 row);
void setupMoon(u8 prio);       // moon+glow OBJ (prio 0 = behind mountains for play; 1 = in front for title)
void armSkyGradient(void);     // COLOR-MATH sky gradient on HDMA ch6 (shared by play + title)

// ---- player.c : the hero sprite ----
u8 *heroFrameSrc(u8 f);
void setupHero(void);          // load hero palette + frame 0 into the OBJ slot (OBJ0/OBJ4)

// ---- enemy.c : demo-size (64x64) enemies ----
// Each enemy is a 128-wide CONTIGUOUS band (skeleton in the left 64x64, right 64 blank) uploaded in two 2KB
// halves like the hero -- reliable in the music-shortened VBlank, unlike 8 strided per-row DMAs. Two bands
// fit the 0x1000..0x2000 OBJ region -> 2 on-screen enemies (4 needs WRAM-compositing, a later pass).
#define ENEMY_SLOTS    2
#define ENEMY_PAL      2       // OBJ palette 2 (CGRAM 128+32); hero = 0, moon = 1
// OAM slot order = sprite z-order (lower id = drawn IN FRONT). The demo draws enemies + their death poof
// ON TOP of the hero (the poof pops at the sword tip), so enemies take the front slots and the hero sits
// behind them. Moon is last (it's up in the sky, never overlaps anyone).
#define ENEMY_OAM_BASE 0       // enemy OBJ ids 0,4  (entries 0,1) -- IN FRONT of the hero
#define HERO_OAM       8       // hero  OBJ ids 8,12 (entries 2,3) -- behind the enemies/poof
#define MOON_OAM       16      // moon  OBJ id 16    (entry 4)
u8 *skeletonFrameSrc(u8 f);
void enemyInit(void);          // load enemy palette + clear the pool + spawn flags
void enemyUpdate(void);        // tick enemy animation/AI (main loop)
s8 enemyCombat(u8 attacking, u8 invuln);   // kills enemies in reach; returns knockback dir if the hero is hit
void enemyDraw(void);          // position the enemy OBJs (camera-relative, main loop)
void enemyVBlankUpload(u8 streaming);   // upload one pending enemy frame (VBlank; skipped while streaming)

#endif
