// generated by tools/adapt_hero.py -- 2-sprite hero, head@x64 feet@y52
#define HERO_FRAMES 21
#define HERO_FEET_X 64
#define HERO_FEET_Y 52
#define A_IDLE_F 0
#define A_IDLE_N 4
#define A_RUN_F 4
#define A_RUN_N 6
#define A_JUMP_F 10
#define A_JUMP_N 4
#define A_CROUCH_F 14
#define A_CROUCH_N 1
#define A_ATTACK_F 15
#define A_ATTACK_N 5
#define A_HURT_F 20
#define A_HURT_N 1
