// generated by tools/adapt_enemy.py -- skeleton: 64x64 OBJ frames, feet at row 60
#define SK_FRAMES 14
#define SK_FEET_BY 60
#define SK_RISE_F 0
#define SK_RISE_N 6
#define SK_WALK_F 6
#define SK_WALK_N 8
