// generated by tools/gen_sky_gradient.py -- dark backdrop floor (CGRAM 0); HDMA adds a per-scanline
// indigo->purple ramp on top of it via $2132 (colour math), never CGRAM.
#define SKY_BACKDROP 0x1401
